name: aira_perpus
description: Aplikasi Pengelolaan Perpustakaan SMPN 03 Sutojayan dengan Flutter.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons premium tambahan
  lucide_icons: ^0.257.0

  # Font modern agar tampilan elegan
  google_fonts: ^6.1.0

  # Database Supabase
  supabase_flutter: ^2.6.0

  # Penyimpanan lokal
  shared_preferences: ^2.2.3

  # Fitur Audio (SoundUtils)
  audioplayers: ^6.0.0

  # Fitur QR & Barcode
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0

  # Ekspor Data
  excel: ^4.0.6
  file_picker: ^8.0.1

  # Cetak PDF
  pdf: ^3.10.8

  # URL Launcher
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#ffffff"
    theme_color: "#1E8A5F"

flutter:
  uses-material-design: true

  # Daftar aset (Gambar & Suara)
  assets:
    - assets/images/
    - assets/audio/